// Public halves of the keypairs generated by scripts/generate-singpass-keys.mjs (run
// 2026-09-16). Safe to expose — these contain no `d` (private key) member. Served at
// /.well-known/jwks.json and registered as the JWKS / Token-based authentication endpoint in
// the Singpass Developer Portal once the app itself is created there.
//
// Rotate the same way Loanify does: add the new key here without removing the old one, wait an
// hour, then switch signing/decryption over to it (SINGPASS_SIG_PRIVATE_JWK /
// SINGPASS_ENC_PRIVATE_JWK) before removing the old key.
export const singpassPublicJwks = {
  keys: [
    {
      kty: "EC",
      x: "2MnosDcz4tOUZTOk-ZFlUdn89KdZUPQeDVsdVksJo-A",
      y: "P3TCTSuBuTmzELG0-Csj9lTOyjLKC2B1gQw2QztSEks",
      crv: "P-256",
      kid: "hms-credit-sig-2026-58525bf6",
      use: "sig",
      alg: "ES256",
    },
    {
      kty: "EC",
      x: "AIb_WIt6SNUGRTNArk2dpEZSdNW7OtTMAAySe-fKoGA",
      y: "2RcWpEUosTlvgO8i1oO_1izIliKs4EH-w5jqCiCkc2A",
      crv: "P-256",
      kid: "hms-credit-enc-2026-d239774d",
      use: "enc",
      alg: "ECDH-ES+A256KW",
    },
  ],
};
